# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'V2EX' do
	pod 'AFNetworking', '~> 3.0'
    pod 'TTTAttributedLabel', '~> 2.0.0'
    pod 'YYCategories', '~> 1.0.0'
    pod 'BlocksKit', '~> 2.2.0'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'FXKeychain', '~> 1.5.0'
    pod 'SIHTMLParser', '~> 1.0'
    pod 'Aspects', '~> 1.4.0'
    pod 'SDWebImage', '~> 3.8.0'
    pod 'YYModel', '~> 1.0.0'
    pod 'CocoaLumberjack', '~> 3.0.0'
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']
    pod 'IQKeyboardManager', '~> 4.0.0'
    pod 'GDPerformanceView', '~> 1.3.0'
    pod 'DZNEmptyDataSet', '~> 1.8.0'
    pod 'IDMPhotoBrowser', '~> 1.10.0'
    pod 'RegexKitLite', '~> 4.0'
    pod 'libextobjc', '~> 0.4.0'
end
